#job0:
#  script: "pip3 install -r requirements;python3.5 setup.py install;./key_to_file.py;./tests/user.py"
before_script:
	- pip3 install -r requirements
	- python3.5 setup.py develop
job0:
	script: 
		- ./key_to_file.py
		- ./tests/user.py
	
