job0:
  script: "pip install --upgrade pip"
job1:
  script: "apt-get -qq -y install python3-openssl"
job2:
  script: "pip install -r requirements"
job3:
  script: "python3.5 setup.py install"
  script: "./testapi.py"
