before_script: 
  - "pip3 install -r requirements.txt"
  - "python3.5 setup.py develop"
job0: 
  script: 
    - ./key_to_file.py
    - ./tests/test_query_user.py
    - ./tests/test_query_authority.py
    - ./tests/test_query_project.py
    - ./tests/test_query_slice.py
    - ./tests/test_model_user.py
    - ./tests/test_model_authority.py
    - ./tests/test_model_slice.py
    - ./tests/test_model_project.py
