job0:
  script: "virtualenv -p /usr/bin/python3 py3env"
  script: "source py3env/bin/activate"
  script: "pip install --upgrade pip"
  script: "pip install -r requirements"
job1:
  script: "python3.5 setup.py install"
  script: "./testapi.py"
