class registry():
    pass

onelab = registry()
fed4fire = registry()

#sm = http://194.199.16.164:12346
onelab.iotlab = {   'code_tag': '-',
    'code_url': 'git://git.onelab.eu/sfa.git',
    'geni_ad_rspec_versions': [   {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                      'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/ad.xsd',
                                      'type': 'Fedrica',
                                      'version': '2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '2'},
                                  {   'extensions': [],
                                      'namespace': '',
                                      'schema': '',
                                      'type': 'SFA',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'GENI',
                                      'version': '3'},
                                  {   'extensions': [],
                                      'namespace': 'openflow',
                                      'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                      'type': 'OFELIA',
                                      'version': '1'},
                                  {   'extensions': [],
                                      'namespace': None,
                                      'schema': None,
                                      'type': 'NITOS',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://senslab.info/resources/rspec/1/ad.xsd',
                                      'type': 'Iotlab',
                                      'version': '1'}],
    'geni_allocate': 'geni_many',
    'geni_api': 3,
    'geni_api_versions': {   '3': 'http://localhost:12346'},
    'geni_credential_types': [   {   'geni_type': 'geni_sfa',
                                     'geni_version': '2'},
                                 {   'geni_type': 'geni_sfa',
                                     'geni_version': '3'}],
    'geni_handles_speaksfor': True,
    'geni_request_rspec_versions': [   {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                           'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/request.xsd',
                                           'type': 'Fedrica',
                                           'version': '2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '2'},
                                       {   'extensions': [],
                                           'namespace': '',
                                           'schema': '',
                                           'type': 'SFA',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'GENI',
                                           'version': '3'},
                                       {   'extensions': [],
                                           'namespace': 'openflow',
                                           'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                           'type': 'OFELIA',
                                           'version': '1'},
                                       {   'extensions': [],
                                           'namespace': None,
                                           'schema': None,
                                           'type': 'NITOS',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://senslab.info/resources/rspec/1/request.xsd',
                                           'type': 'Iotlab',
                                           'version': '1'}],
    'geni_single_allocation': 0,
    'hostname': 'srvsfa',
    'hrn': 'iotlab',
    'interface': 'aggregate',
    'sfa': 3,
    'testbed': 'iotlab',
    'urn': 'urn:publicid:IDN+iotlab+authority+am'}

#sm = 157.193.171.131:12369/protogeni/xmlrpc/am/2.0
onelab.wilab2 ={   'code_tag': '417e3e6864d0516206fe1a4ac124080d9e023e06',
    'geni_ad_rspec_versions': [   {   'extensions': [],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/0.1',
                                      'schema': 'http://www.protogeni.net/resources/rspec/0.1/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '0.1'},
                                  {   'extensions': [],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/0.2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/0.2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '0.2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'GENI',
                                      'version': '3'}],
    'geni_api': 2,
    'geni_api_versions': {   '1': 'https://www.wilab2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/1.0',
                             '2': 'https://www.wilab2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/2.0',
                             '3': 'https://www.wilab2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/3.0'},
    'geni_request_rspec_versions': [   {   'extensions': [],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/0.1',
                                           'schema': 'http://www.protogeni.net/resources/rspec/0.1/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '0.1'},
                                       {   'extensions': [],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/0.2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/0.2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '0.2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'GENI',
                                           'version': '3'}],
    'hostname': 'boss.wilab2.ilabt.iminds.be',
    'hrn': 'iminds-wilab2.cm',
    'interface': 'aggregate',
    'url': 'https://www.wilab2.ilabt.iminds.be:12369/protogeni/xmlrpc/am',
    'urn': 'urn:publicid:IDN+wilab2.ilabt.iminds.be+authority+cm'}

#sm = http://sfa3.planet-lab.eu:12346/
onelab.plev3 = {   'code_tag': '3.1-20',
    'code_url': 'git://git.onelab.eu/sfa.git@sfa-3.1-20',
    'geni_ad_rspec_versions': [   {   'extensions': [],
                                      'namespace': '',
                                      'schema': '',
                                      'type': 'SFA',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://senslab.info/resources/rspec/1/ad.xsd',
                                      'type': 'Iotlab',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                      'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/ad.xsd',
                                      'type': 'Fedrica',
                                      'version': '2'},
                                  {   'extensions': [],
                                      'namespace': None,
                                      'schema': None,
                                      'type': 'NITOS',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'GENI',
                                      'version': '3'},
                                  {   'extensions': [],
                                      'namespace': 'openflow',
                                      'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                      'type': 'OFELIA',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '2'}],
    'geni_allocate': 'geni_many',
    'geni_api': 3,
    'geni_api_versions': {   '3': 'http://sfa3.planet-lab.eu:12346'},
    'geni_credential_types': [   {   'geni_type': 'geni_sfa',
                                     'geni_version': '2'},
                                 {   'geni_type': 'geni_sfa',
                                     'geni_version': '3'}],
    'geni_handles_speaksfor': True,
    'geni_request_rspec_versions': [   {   'extensions': [],
                                           'namespace': '',
                                           'schema': '',
                                           'type': 'SFA',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://senslab.info/resources/rspec/1/request.xsd',
                                           'type': 'Iotlab',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                           'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/request.xsd',
                                           'type': 'Fedrica',
                                           'version': '2'},
                                       {   'extensions': [],
                                           'namespace': None,
                                           'schema': None,
                                           'type': 'NITOS',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'GENI',
                                           'version': '3'},
                                       {   'extensions': [],
                                           'namespace': 'openflow',
                                           'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                           'type': 'OFELIA',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '2'}],
    'geni_single_allocation': 0,
    'hostname': 'ple-sfa3.pl.sophia.inria.fr',
    'hrn': 'ple',
    'interface': 'aggregate',
    'sfa': 3,
    'testbed': 'myplc',
    'urn': 'urn:publicid:IDN+ple+authority+am'}

#sm = http://nitlab.inf.uth.gr:8001/RPC2
onelab.nitosbroker1 = {   'code_tag': 'https://github.com/dostavro/omf_sfa/tree/xmpp',
    'f4f_endorsed_tools': [   {   'tool_homepage': 'http://mytestbed.net/',
                                  'tool_logo': 'http://mytestbed.net/omf-images/omf-logo.png',
                                  'tool_name': 'OMF',
                                  'tool_version': '5.4, 6.0'},
                              {   'tool_homepage': 'http://mytestbed.net/projects/oml/wiki',
                                  'tool_logo': 'http://mytestbed.net/attachments/download/797/oml.png',
                                  'tool_name': 'OML',
                                  'tool_version': 2.1}],
    'f4f_testbed_description': 'NITOS testbed currently consists of 50 operational wireless nodes, which are based on commercial Wifi cards and Linux open source drivers. The testbed is designed to achieve reproducibility of experimentation, while also supporting evaluation of protocols and applications in real world settings. NITOS testbed is deployed at the exterior of the University of Thessaly (UTH) campus building.',
    'f4f_testbed_picture': 'http://nitlab.inf.uth.gr/NITlab/images/stories/nitlab/nitos_topology.png',
    'geni_ad_rspec_versions': [   {   'extensions': [   'http://nitlab.inf.uth.gr/schema/sfa/rspec/1/ad-reservation.xsd'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'geni',
                                      'version': '3'}],
    'geni_api': 2,
    'geni_api_versions': {   '2': 'http://nitlab.inf.uth.gr:8001/RPC2'},
    'geni_request_rspec_versions': [   {   'extensions': [   'http://nitlab.inf.uth.gr/schema/sfa/rspec/1/request-reservation.xsd'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'geni',
                                           'version': '3'}],
    'hostname': 'http://nitlab.inf.uth.gr',
    'hrn': 'nitos',
    'omf_am': '0.1',
    'urn': 'urn:publicid:IDN+omf:nitos+authority+cm'}

#sm = http://griffin.ipv6.lip6.fr:8001/RPC2
onelab.nitosbroker2 = {   'code_tag': 'https://github.com/dostavro/omf_sfa/tree/xmpp',
    'f4f_endorsed_tools': {   'tool_homepage': 'http://mytestbed.net/',
                              'tool_logo': 'http://mytestbed.net/omf-images/omf-logo.png',
                              'tool_name': 'OMF',
                              'tool_version': 6.0},
    'f4f_testbed_description': u'Paris FIT-NITOS testbed currently consists of 40 operational wireless nodes, which are based on commercial Wifi cards and Linux open source drivers. The testbed is designed to achieve reproducibility of experimentation, while also supporting evaluation of protocols and applications in real world settings. Paris FIT-NITOS testbed is deployed at the interior of the Universit\xe9 Pierre et MarieCurie (UPMC) campus building.',
    'geni_ad_rspec_versions': [   {   'extensions': [   'http://nitlab.inf.uth.gr/schema/sfa/rspec/1/ad-reservation.xsd'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'geni',
                                      'version': '3'}],
    'geni_api': 2,
    'geni_api_versions': {   '2': 'http://griffin.ipv6.lip6.fr:8001/RPC2'},
    'geni_request_rspec_versions': [   {   'extensions': [   'http://nitlab.inf.uth.gr/schema/sfa/rspec/1/request-reservation.xsd'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'geni',
                                           'version': '3'}],
    'hostname': 'http://griffin.ipv6.lip6.fr',
    'hrn': 'paris.fit-nitos.fr',
    'omf_am': '0.1',
    'urn': 'urn:publicid:IDN+omf:paris.fit-nitos.fr+authority+cm'}

#sm = http://iot.snsi.iii.org.tw:12346
onelab.iii = {   'code_tag': '-',
    'code_url': 'git://git.onelab.eu/sfa.git',
    'geni_ad_rspec_versions': [   {   'extensions': [],
                                      'namespace': '',
                                      'schema': '',
                                      'type': 'SFA',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                      'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/ad.xsd',
                                      'type': 'Fedrica',
                                      'version': '2'},
                                  {   'extensions': [],
                                      'namespace': None,
                                      'schema': None,
                                      'type': 'NITOS',
                                      'version': '1'},
                                  {   'extensions': [],
                                      'namespace': 'openflow',
                                      'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                      'type': 'OFELIA',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'GENI',
                                      'version': '3'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://senslab.info/resources/rspec/1/ad.xsd',
                                      'type': 'Iotlab',
                                      'version': '1'}],
    'geni_allocate': 'geni_many',
    'geni_api': 3,
    'geni_api_versions': {   '3': 'http://localhost:12346'},
    'geni_credential_types': [   {   'geni_type': 'geni_sfa',
                                     'geni_version': '2'},
                                 {   'geni_type': 'geni_sfa',
                                     'geni_version': '3'}],
    'geni_handles_speaksfor': True,
    'geni_request_rspec_versions': [   {   'extensions': [],
                                           'namespace': '',
                                           'schema': '',
                                           'type': 'SFA',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                           'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/request.xsd',
                                           'type': 'Fedrica',
                                           'version': '2'},
                                       {   'extensions': [],
                                           'namespace': None,
                                           'schema': None,
                                           'type': 'NITOS',
                                           'version': '1'},
                                       {   'extensions': [],
                                           'namespace': 'openflow',
                                           'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                           'type': 'OFELIA',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'GENI',
                                           'version': '3'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://senslab.info/resources/rspec/1/request.xsd',
                                           'type': 'Iotlab',
                                           'version': '1'}],
    'geni_single_allocation': 0,
    'hostname': 'srvsfa',
    'hrn': 'iii',
    'interface': 'aggregate',
    'sfa': 3,
    'testbed': 'iii',
    'urn': 'urn:publicid:IDN+iii+authority+am'}


#sm = http://157.159.249.151:12346/
onelab.fitevry = {   'code_tag': '3.1-15',
    'code_url': 'git://git.onelab.eu/sfa.git',
    'geni_ad_rspec_versions': [   {   'extensions': [],
                                      'namespace': '',
                                      'schema': '',
                                      'type': 'SFA',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'GENI',
                                      'version': '3'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://senslab.info/resources/rspec/1/ad.xsd',
                                      'type': 'Iotlab',
                                      'version': '1'},
                                  {   'extensions': [],
                                      'namespace': 'openstack',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'KOREN',
                                      'version': '1'},
                                  {   'extensions': [],
                                      'namespace': 'openflow',
                                      'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                      'type': 'OFELIA',
                                      'version': '1'},
                                  {   'extensions': [],
                                      'namespace': None,
                                      'schema': None,
                                      'type': 'NITOS',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                      'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/ad.xsd',
                                      'type': 'Fedrica',
                                      'version': '2'}],
    'geni_allocate': 'geni_many',
    'geni_api': 3,
    'geni_api_versions': {   '3': 'http://localhost:12346'},
    'geni_credential_types': [   {   'geni_type': 'geni_sfa',
                                     'geni_version': '2'},
                                 {   'geni_type': 'geni_sfa',
                                     'geni_version': '3'}],
    'geni_handles_speaksfor': True,
    'geni_request_rspec_versions': [   {   'extensions': [],
                                           'namespace': '',
                                           'schema': '',
                                           'type': 'SFA',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'GENI',
                                           'version': '3'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://senslab.info/resources/rspec/1/request.xsd',
                                           'type': 'Iotlab',
                                           'version': '1'},
                                       {   'extensions': [],
                                           'namespace': 'openstack',
                                           'schema': 'http://203.255.254.100:8888/resources/sfa/rspecs/openstack/openstack.xsd',
                                           'type': 'KOREN',
                                           'version': '1'},
                                       {   'extensions': [],
                                           'namespace': 'openflow',
                                           'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                           'type': 'OFELIA',
                                           'version': '1'},
                                       {   'extensions': [],
                                           'namespace': None,
                                           'schema': None,
                                           'type': 'NITOS',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                           'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/request.xsd',
                                           'type': 'Fedrica',
                                           'version': '2'}],
    'geni_single_allocation': 0,
    'hostname': 'fit-loic-version',
    'hrn': 'ncf',
    'interface': 'aggregate',
    'sfa': 3,
    'testbed': 'openstack',
    'urn': 'urn:publicid:IDN+ncf+authority+am'}


fed4fire.wilab2 = {   'code_tag': '417e3e6864d0516206fe1a4ac124080d9e023e06',
    'geni_ad_rspec_versions': [   {   'extensions': [],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/0.1',
                                      'schema': 'http://www.protogeni.net/resources/rspec/0.1/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '0.1'},
                                  {   'extensions': [],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/0.2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/0.2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '0.2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'GENI',
                                      'version': '3'}],
    'geni_api': 2,
    'geni_api_versions': {   '1': 'https://www.wilab2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/1.0',
                             '2': 'https://www.wilab2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/2.0',
                             '3': 'https://www.wilab2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/3.0'},
    'geni_request_rspec_versions': [   {   'extensions': [],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/0.1',
                                           'schema': 'http://www.protogeni.net/resources/rspec/0.1/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '0.1'},
                                       {   'extensions': [],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/0.2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/0.2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '0.2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'GENI',
                                           'version': '3'}],
    'hostname': 'boss.wilab2.ilabt.iminds.be',
    'hrn': 'iminds-wilab2.cm',
    'interface': 'aggregate',
    'url': 'https://www.wilab2.ilabt.iminds.be:12369/protogeni/xmlrpc/am',
    'urn': 'urn:publicid:IDN+wilab2.ilabt.iminds.be+authority+cm'}


#sm = http://www.wall2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/2.0
onelab.virtualwall = {   'code_tag': '311201a3dceacf3fc3b6538c55013343328a4619',
    'geni_ad_rspec_versions': [   {   'extensions': [],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/0.1',
                                      'schema': 'http://www.protogeni.net/resources/rspec/0.1/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '0.1'},
                                  {   'extensions': [],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/0.2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/0.2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '0.2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1',
                                                        'http://www.protogeni.net/resources/rspec/ext/site-info/1'],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1',
                                                        'http://www.protogeni.net/resources/rspec/ext/site-info/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'GENI',
                                      'version': '3'}],
    'geni_api': 2,
    'geni_api_versions': {   '1': 'https://www.wall2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/1.0',
                             '2': 'https://www.wall2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/2.0',
                             '3': 'https://www.wall2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/3.0'},
    'geni_request_rspec_versions': [   {   'extensions': [],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/0.1',
                                           'schema': 'http://www.protogeni.net/resources/rspec/0.1/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '0.1'},
                                       {   'extensions': [],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/0.2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/0.2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '0.2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'GENI',
                                           'version': '3'}],
    'hostname': 'boss.wall2.ilabt.iminds.be',
    'hrn': 'iminds-wall2.cm',
    'interface': 'aggregate',
    'url': 'https://www.wall2.ilabt.iminds.be:12369/protogeni/xmlrpc/am',
    'urn': 'urn:publicid:IDN+wall2.ilabt.iminds.be+authority+cm'}


#sm = http://www.wall2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/3.0
onelab.virtualwallv3 = {   'code_tag': '311201a3dceacf3fc3b6538c55013343328a4619',
    'geni_ad_rspec_versions': [   {   'extensions': [],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/0.1',
                                      'schema': 'http://www.protogeni.net/resources/rspec/0.1/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '0.1'},
                                  {   'extensions': [],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/0.2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/0.2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '0.2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1',
                                                        'http://www.protogeni.net/resources/rspec/ext/site-info/1'],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1',
                                                        'http://www.protogeni.net/resources/rspec/ext/site-info/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'GENI',
                                      'version': '3'}],
    'geni_allocate': 'geni_disjoint',
    'geni_api': 3,
    'geni_api_versions': {   '1': 'https://www.wall2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/1.0',
                             '2': 'https://www.wall2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/2.0',
                             '3': 'https://www.wall2.ilabt.iminds.be:12369/protogeni/xmlrpc/am/3.0'},
    'geni_credential_types': [   {   'geni_type': 'geni_sfa',
                                     'geni_version': '2'},
                                 {   'geni_type': 'geni_sfa',
                                     'geni_version': '3'}],
    'geni_request_rspec_versions': [   {   'extensions': [],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/0.1',
                                           'schema': 'http://www.protogeni.net/resources/rspec/0.1/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '0.1'},
                                       {   'extensions': [],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/0.2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/0.2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '0.2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/emulab/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'GENI',
                                           'version': '3'}],
    'geni_single_allocation': '1',
    'hostname': 'boss.wall2.ilabt.iminds.be',
    'hrn': 'iminds-wall2.cm',
    'interface': 'aggregate',
    'url': 'https://www.wall2.ilabt.iminds.be:12369/protogeni/xmlrpc/am',
    'urn': 'urn:publicid:IDN+wall2.ilabt.iminds.be+authority+cm'}


#sm = http://vnews.netmode.ntua.gr:8001/RPC2
fed4fire.netnode = {   'code_tag': 'https://github.com/ardadouk/omf_sfa/tree/xmpp',
    'f4f_endorsed_tools': [   {   'tool_homepage': 'http://mytestbed.net/',
                                  'tool_logo': 'http://mytestbed.net/omf-images/omf-logo.png',
                                  'tool_name': 'OMF',
                                  'tool_version': '5.4, 6.0'},
                              {   'tool_homepage': 'http://mytestbed.net/projects/oml/wiki',
                                  'tool_logo': 'http://mytestbed.net/attachments/download/797/oml.png',
                                  'tool_name': 'OML',
                                  'tool_version': 2.1}],
    'f4f_testbed_description': 'NETMODE testbed currently consists of 20 operational wireless nodes, which are based on commercial Wifi cards and Linux open source drivers. The wireless nodes are scattered around the 3rd floor and the roof of the ECE building at the National Technical University of Athens (NTUA).',
    'f4f_testbed_picture': 'http://vnews.netmode.ntua.gr/testbed.jpg',
    'geni_ad_rspec_versions': [   {   'extensions': [   'http://nitlab.inf.uth.gr/schema/sfa/rspec/1/ad-reservation.xsd'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'geni',
                                      'version': '3'}],
    'geni_api': 2,
    'geni_api_versions': {   '2': 'http://vnews.netmode.ntua.gr:8001/RPC2'},
    'geni_request_rspec_versions': [   {   'extensions': [   'http://nitlab.inf.uth.gr/schema/sfa/rspec/1/request-reservation.xsd'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'geni',
                                           'version': '3'}],
    'hostname': 'http://vnews.netmode.ntua.gr',
    'hrn': 'omf.netmode',
    'omf_am': '0.1',
    'urn': 'urn:publicid:IDN+omf:netmode+authority+am'}


#sm = http://nitlab.inf.uth.gr:8001/RPC2
fed4fire.nitosbroker1 = {   'code_tag': 'https://github.com/dostavro/omf_sfa/tree/xmpp',
    'f4f_endorsed_tools': [   {   'tool_homepage': 'http://mytestbed.net/',
                                  'tool_logo': 'http://mytestbed.net/omf-images/omf-logo.png',
                                  'tool_name': 'OMF',
                                  'tool_version': '5.4, 6.0'},
                              {   'tool_homepage': 'http://mytestbed.net/projects/oml/wiki',
                                  'tool_logo': 'http://mytestbed.net/attachments/download/797/oml.png',
                                  'tool_name': 'OML',
                                  'tool_version': 2.1}],
    'f4f_testbed_description': 'NITOS testbed currently consists of 50 operational wireless nodes, which are based on commercial Wifi cards and Linux open source drivers. The testbed is designed to achieve reproducibility of experimentation, while also supporting evaluation of protocols and applications in real world settings. NITOS testbed is deployed at the exterior of the University of Thessaly (UTH) campus building.',
    'f4f_testbed_picture': 'http://nitlab.inf.uth.gr/NITlab/images/stories/nitlab/nitos_topology.png',
    'geni_ad_rspec_versions': [   {   'extensions': [   'http://nitlab.inf.uth.gr/schema/sfa/rspec/1/ad-reservation.xsd'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'geni',
                                      'version': '3'}],
    'geni_api': 2,
    'geni_api_versions': {   '2': 'http://nitlab.inf.uth.gr:8001/RPC2'},
    'geni_request_rspec_versions': [   {   'extensions': [   'http://nitlab.inf.uth.gr/schema/sfa/rspec/1/request-reservation.xsd'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'geni',
                                           'version': '3'}],
    'hostname': 'http://nitlab.inf.uth.gr',
    'hrn': 'nitos',
    'omf_am': '0.1',
    'urn': 'urn:publicid:IDN+omf:nitos+authority+cm'}

#sm = http://sfa3.planet-lab.eu:12346/
fed4fire.plev3 = {   'code_tag': '3.1-20',
    'code_url': 'git://git.onelab.eu/sfa.git@sfa-3.1-20',
    'geni_ad_rspec_versions': [   {   'extensions': [],
                                      'namespace': '',
                                      'schema': '',
                                      'type': 'SFA',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://senslab.info/resources/rspec/1/ad.xsd',
                                      'type': 'Iotlab',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                      'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/ad.xsd',
                                      'type': 'Fedrica',
                                      'version': '2'},
                                  {   'extensions': [],
                                      'namespace': None,
                                      'schema': None,
                                      'type': 'NITOS',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'GENI',
                                      'version': '3'},
                                  {   'extensions': [],
                                      'namespace': 'openflow',
                                      'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                      'type': 'OFELIA',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '2'}],
    'geni_allocate': 'geni_many',
    'geni_api': 3,
    'geni_api_versions': {   '3': 'http://sfa3.planet-lab.eu:12346'},
    'geni_credential_types': [   {   'geni_type': 'geni_sfa',
                                     'geni_version': '2'},
                                 {   'geni_type': 'geni_sfa',
                                     'geni_version': '3'}],
    'geni_handles_speaksfor': True,
    'geni_request_rspec_versions': [   {   'extensions': [],
                                           'namespace': '',
                                           'schema': '',
                                           'type': 'SFA',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://senslab.info/resources/rspec/1/request.xsd',
                                           'type': 'Iotlab',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                           'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/request.xsd',
                                           'type': 'Fedrica',
                                           'version': '2'},
                                       {   'extensions': [],
                                           'namespace': None,
                                           'schema': None,
                                           'type': 'NITOS',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'GENI',
                                           'version': '3'},
                                       {   'extensions': [],
                                           'namespace': 'openflow',
                                           'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                           'type': 'OFELIA',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '2'}],
    'geni_single_allocation': 0,
    'hostname': 'ple-sfa3.pl.sophia.inria.fr',
    'hrn': 'ple',
    'interface': 'aggregate',
    'sfa': 3,
    'testbed': 'myplc',
    'urn': 'urn:publicid:IDN+ple+authority+am'}

#sm = http://157.159.232.164:12346
fed4fire.telecomevry = {   'code_tag': '3.1-15',
    'code_url': 'git://git.onelab.eu/sfa.git',
    'geni_ad_rspec_versions': [   {   'extensions': [],
                                      'namespace': '',
                                      'schema': '',
                                      'type': 'SFA',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'GENI',
                                      'version': '3'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                      'schema': 'http://www.protogeni.net/resources/rspec/2/ad.xsd',
                                      'type': 'ProtoGENI',
                                      'version': '2'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                      'namespace': 'http://www.geni.net/resources/rspec/3',
                                      'schema': 'http://senslab.info/resources/rspec/1/ad.xsd',
                                      'type': 'Iotlab',
                                      'version': '1'},
                                  {   'extensions': [],
                                      'namespace': 'openstack',
                                      'schema': 'http://www.geni.net/resources/rspec/3/ad.xsd',
                                      'type': 'KOREN',
                                      'version': '1'},
                                  {   'extensions': [],
                                      'namespace': 'openflow',
                                      'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                      'type': 'OFELIA',
                                      'version': '1'},
                                  {   'extensions': [],
                                      'namespace': None,
                                      'schema': None,
                                      'type': 'NITOS',
                                      'version': '1'},
                                  {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                        'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                      'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                      'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/ad.xsd',
                                      'type': 'Fedrica',
                                      'version': '2'}],
    'geni_allocate': 'geni_many',
    'geni_api': 3,
    'geni_api_versions': {   '3': 'http://localhost:12346'},
    'geni_credential_types': [   {   'geni_type': 'geni_sfa',
                                     'geni_version': '2'},
                                 {   'geni_type': 'geni_sfa',
                                     'geni_version': '3'}],
    'geni_handles_speaksfor': True,
    'geni_request_rspec_versions': [   {   'extensions': [],
                                           'namespace': '',
                                           'schema': '',
                                           'type': 'SFA',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://www.geni.net/resources/rspec/3/request.xsd',
                                           'type': 'GENI',
                                           'version': '3'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://www.protogeni.net/resources/rspec/2',
                                           'schema': 'http://www.protogeni.net/resources/rspec/2/request.xsd',
                                           'type': 'ProtoGENI',
                                           'version': '2'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1'],
                                           'namespace': 'http://www.geni.net/resources/rspec/3',
                                           'schema': 'http://senslab.info/resources/rspec/1/request.xsd',
                                           'type': 'Iotlab',
                                           'version': '1'},
                                       {   'extensions': [],
                                           'namespace': 'openstack',
                                           'schema': 'http://203.255.254.100:8888/resources/sfa/rspecs/openstack/openstack.xsd',
                                           'type': 'KOREN',
                                           'version': '1'},
                                       {   'extensions': [],
                                           'namespace': 'openflow',
                                           'schema': 'https://github.com/fp7-ofelia/ocf/blob/ocf.rspecs/openflow/schemas/ad.xsd',
                                           'type': 'OFELIA',
                                           'version': '1'},
                                       {   'extensions': [],
                                           'namespace': None,
                                           'schema': None,
                                           'type': 'NITOS',
                                           'version': '1'},
                                       {   'extensions': [   'http://www.protogeni.net/resources/rspec/ext/flack/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/planetlab/1',
                                                             'http://www.planet-lab.org/resources/sfa/ext/plos/1'],
                                           'namespace': 'http://sorch.netmode.ntua.gr/ws/RSpec',
                                           'schema': 'http://sorch.netmode.ntua.gr/ws/RSpec/request.xsd',
                                           'type': 'Fedrica',
                                           'version': '2'}],
    'geni_single_allocation': 0,
    'hostname': 'fit-loic-version',
    'hrn': 'ncf',
    'interface': 'aggregate',
    'sfa': 3,
    'testbed': 'openstack',
    'urn': 'urn:publicid:IDN+ncf+authority+am'}

if __name__ == '__main__':
    '''
    Find the common key in versions
    '''
    ams = []
    for _, version in onelab.__dict__.items():
        ams += [set(version.keys())]
    for _, version in fed4fire.__dict__.items():
        ams += [set(version.keys())]
    print(set.intersection(*ams))
